[general]
live_config_reload = true

[window]
padding = { x = 16, y = 16 }
dynamic_padding = true
decorations = "None"
opacity = 0.75
startup_mode = "Maximized"

[font]
size = 16

[colors.primary]
background = "#181825"
[colors.cursor]
cursor = "#94e2d5"
